# Generated by Django 4.2.28 on 2026-05-27 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavadinimas', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('last_name', 'first_name'),
            },
        ),
        migrations.CreateModel(
            name='Klase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavadinimas', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Klasė',
                'verbose_name_plural': 'Klasės',
                'ordering': ('pavadinimas',),
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavadinimas', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vardas', models.CharField(max_length=50)),
                ('pavarde', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, default='', help_text='Įvedųs email, mokytojas prisijungęs matys atskirą skydelį įrašynėti,trinti ar keisti savo laikus', max_length=254, verbose_name='Mokytojo Gmail')),
                ('dalykai', models.ManyToManyField(blank=True, to='reservations.subject')),
                ('kabinetas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.cabinet')),
                ('klases', models.ManyToManyField(blank=True, to='reservations.klase', verbose_name='Klasės')),
            ],
            options={
                'ordering': ('pavarde', 'vardas'),
            },
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('interval', models.IntegerField(choices=[(10, '10 minučių'), (20, '20 minučių'), (30, '30 minučių'), (40, '40 minučių'), (50, '50 minučių'), (60, '1 valanda')], default=10)),
                ('tipas', models.CharField(choices=[('individualus', 'Individualus pokalbis'), ('dalykininku', 'Dalykininku pokalbis')], default='individualus', max_length=20, verbose_name='Pokalbio tipas')),
                ('mokytojai', models.ManyToManyField(related_name='working_hours', to='reservations.teacher', verbose_name='Teachers')),
            ],
            options={
                'verbose_name': 'Working hours',
                'verbose_name_plural': 'Working hours',
                'ordering': ('date', 'start_time'),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.child')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='child',
            name='klase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.klase', verbose_name='Klasė'),
        ),
        migrations.AddField(
            model_name='child',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Break',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('description', models.CharField(blank=True, max_length=100)),
                ('working_hours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='reservations.workinghours')),
            ],
            options={
                'ordering': ('start_time',),
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reserved_first_name', models.CharField(blank=True, max_length=50)),
                ('reserved_last_name', models.CharField(blank=True, max_length=50)),
                ('reserved_class', models.CharField(blank=True, max_length=20)),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.child')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.teacher')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('date', 'time'),
                'unique_together': {('teacher', 'date', 'time')},
            },
        ),
    ]
