# Generated by Django 4.2.28 on 2026-05-27 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='klase',
            name='aukletojas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auklejamos_klases', to='reservations.teacher', verbose_name='Klasės auklėtojas'),
        ),
    ]
