# Generated by Django 4.2.28 on 2026-07-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_klase_aukletojas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinghours',
            name='interval',
            field=models.IntegerField(choices=[(15, '15 minučių'), (30, '30 minučių'), (45, '45 minutės'), (60, '60 minučių')], default=10),
        ),
    ]
