# Generated by Django 6.0.6 on 2026-07-02 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_alter_workinghours_interval'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='klase',
            options={'ordering': ('pavadinimas',), 'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AddField(
            model_name='reservation',
            name='cabinet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.cabinet', verbose_name='Kabinetas'),
        ),
    ]
