# Generated by Django 6.0.6 on 2026-07-02 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_alter_klase_options_reservation_cabinet'),
    ]

    operations = [
        migrations.AddField(
            model_name='workinghours',
            name='cabinet',
            field=models.ForeignKey(blank=True, help_text='Jei nepasirinkta, bus naudojamas mokytojo numatytas kabinetas', null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.cabinet', verbose_name='Kabinetas'),
        ),
    ]
