# Generated by Django 5.2.15 on 2026-09-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_workinghours_cabinet'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeistinasEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Gmail adresas, kuriuo tėvas galės prisijungti', max_length=254, unique=True, verbose_name='El. paštas')),
                ('pastaba', models.CharField(blank=True, default='', help_text='Pvz. vaiko vardas ar klasė, kad būtų aišku kieno tai adresas', max_length=100, verbose_name='Pastaba')),
                ('pridetas', models.DateTimeField(auto_now_add=True, verbose_name='Pridėtas')),
            ],
            options={
                'verbose_name': 'Leistinas el. paštas',
                'verbose_name_plural': 'Leistini el. paštai',
                'ordering': ('email',),
            },
        ),
    ]
