# Generated by Django 5.2.15 on 2026-09-07 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_leistinasemail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leistinasemail',
            options={'ordering': ('email',), 'verbose_name': 'Parent email', 'verbose_name_plural': 'Parents emails'},
        ),
    ]
