# Generated by Django 5.2.15 on 2026-09-10 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_alter_leistinasemail_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='tipas',
            field=models.CharField(choices=[('individualus', 'Individualus pokalbis'), ('dalykininku', 'Dalykininku pokalbis')], default='individualus', max_length=20, verbose_name='Pokalbio tipas'),
        ),
    ]
