# Generated by Django 5.2.15 on 2026-09-25 22:18

import django.db.models.functions.comparison
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_break_pasalintas_laikas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='klase',
            options={'ordering': (models.OrderBy(django.db.models.functions.comparison.Cast('pavadinimas', output_field=models.IntegerField())), models.OrderBy(django.db.models.functions.text.Lower('pavadinimas'))), 'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
    ]
