# Generated by Django 5.2.15 on 2026-09-28 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0010_klase_rusiavimas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vadovas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vardas', models.CharField(max_length=50)),
                ('pavarde', models.CharField(max_length=50)),
                ('pareigos', models.CharField(blank=True, default='', help_text='Pvz. direktorius, pavaduotojas ugdymui', max_length=100, verbose_name='Pareigos')),
                ('email', models.EmailField(help_text='Šiuo adresu prisijungęs vadovas matys savo grafiką ir galės skirti laikus mokytojams', max_length=254, unique=True, verbose_name='Vadovo Gmail')),
            ],
            options={
                'verbose_name': 'Vadovas',
                'verbose_name_plural': 'Vadovai',
                'ordering': ('pavarde', 'vardas'),
            },
        ),
        migrations.CreateModel(
            name='VadovoLaikas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('start_time', models.TimeField(verbose_name='Pradžia')),
                ('end_time', models.TimeField(verbose_name='Pabaiga')),
                ('interval', models.IntegerField(choices=[(15, '15 minučių'), (30, '30 minučių'), (45, '45 minutės'), (60, '60 minučių')], default=15, verbose_name='Laiko intervalas')),
                ('cabinet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.cabinet', verbose_name='Kabinetas')),
                ('vadovas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laikai', to='reservations.vadovas')),
            ],
            options={
                'verbose_name': 'Vadovo laikas',
                'verbose_name_plural': 'Vadovo laikai',
                'ordering': ('date', 'start_time'),
            },
        ),
        migrations.CreateModel(
            name='VadovoPertrauka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('description', models.CharField(blank=True, max_length=100)),
                ('pasalintas_laikas', models.BooleanField(default=False, verbose_name='Pašalintas laikas')),
                ('laikas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='reservations.vadovolaikas')),
            ],
            options={
                'verbose_name': 'Vadovo pertrauka',
                'verbose_name_plural': 'Vadovo pertraukos',
                'ordering': ('start_time',),
            },
        ),
        migrations.CreateModel(
            name='VadovoRezervacija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cabinet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.cabinet')),
                ('mokytojas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vadovo_rezervacijos', to='reservations.teacher')),
                ('vadovas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rezervacijos', to='reservations.vadovas')),
            ],
            options={
                'verbose_name': 'Pokalbis su vadovu',
                'verbose_name_plural': 'Pokalbiai su vadovu',
                'ordering': ('date', 'time'),
                'unique_together': {('vadovas', 'date', 'time')},
            },
        ),
    ]
