# Generated by Django 5.2.15 on 2026-09-28 19:17

import django.db.models.deletion
import django.db.models.functions.comparison
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0011_vadovas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='break',
            options={'ordering': ('start_time',), 'verbose_name': 'Pertrauka', 'verbose_name_plural': 'Pertraukos'},
        ),
        migrations.AlterModelOptions(
            name='cabinet',
            options={'verbose_name': 'Kabinetas', 'verbose_name_plural': 'Kabinetai'},
        ),
        migrations.AlterModelOptions(
            name='child',
            options={'ordering': ('last_name', 'first_name'), 'verbose_name': 'Vaikas', 'verbose_name_plural': 'Vaikai'},
        ),
        migrations.AlterModelOptions(
            name='klase',
            options={'ordering': (models.OrderBy(django.db.models.functions.comparison.Cast('pavadinimas', output_field=models.IntegerField())), models.OrderBy(django.db.models.functions.text.Lower('pavadinimas'))), 'verbose_name': 'Klasė', 'verbose_name_plural': 'Klasės'},
        ),
        migrations.AlterModelOptions(
            name='leistinasemail',
            options={'ordering': ('email',), 'verbose_name': 'Tėvų el. paštas', 'verbose_name_plural': 'Tėvų el. paštai'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profilis', 'verbose_name_plural': 'Profiliai'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ('date', 'time'), 'verbose_name': 'Rezervacija', 'verbose_name_plural': 'Rezervacijos'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Dalykas', 'verbose_name_plural': 'Dalykai'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ('pavarde', 'vardas'), 'verbose_name': 'Mokytojas', 'verbose_name_plural': 'Mokytojai'},
        ),
        migrations.AlterModelOptions(
            name='vadovas',
            options={'ordering': ('pavarde', 'vardas'), 'verbose_name': 'Vadovas', 'verbose_name_plural': 'Vadovas'},
        ),
        migrations.AlterModelOptions(
            name='workinghours',
            options={'ordering': ('date', 'start_time'), 'verbose_name': 'Darbo laikas', 'verbose_name_plural': 'Darbo laikai'},
        ),
        migrations.RemoveField(
            model_name='vadovas',
            name='pareigos',
        ),
        migrations.AlterField(
            model_name='break',
            name='description',
            field=models.CharField(blank=True, max_length=100, verbose_name='Aprašymas'),
        ),
        migrations.AlterField(
            model_name='break',
            name='end_time',
            field=models.TimeField(verbose_name='Pabaiga'),
        ),
        migrations.AlterField(
            model_name='break',
            name='start_time',
            field=models.TimeField(verbose_name='Pradžia'),
        ),
        migrations.AlterField(
            model_name='break',
            name='working_hours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='reservations.workinghours', verbose_name='Darbo laikas'),
        ),
        migrations.AlterField(
            model_name='cabinet',
            name='pavadinimas',
            field=models.CharField(max_length=50, verbose_name='Pavadinimas'),
        ),
        migrations.AlterField(
            model_name='child',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Vardas'),
        ),
        migrations.AlterField(
            model_name='child',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Pavardė'),
        ),
        migrations.AlterField(
            model_name='child',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL, verbose_name='Tėvų paskyra'),
        ),
        migrations.AlterField(
            model_name='klase',
            name='pavadinimas',
            field=models.CharField(max_length=20, verbose_name='Pavadinimas'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='active_child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.child', verbose_name='Aktyvus vaikas'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Vartotojas'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.child', verbose_name='Vaikas'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Sukurta'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reserved_class',
            field=models.CharField(blank=True, max_length=20, verbose_name='Klasė'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reserved_first_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Vaiko vardas'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reserved_last_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Vaiko pavardė'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.teacher', verbose_name='Mokytojas'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.TimeField(verbose_name='Laikas'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Tėvų paskyra'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='pavadinimas',
            field=models.CharField(max_length=100, verbose_name='Pavadinimas'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='dalykai',
            field=models.ManyToManyField(blank=True, to='reservations.subject', verbose_name='Dalykai'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='kabinetas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.cabinet', verbose_name='Kabinetas'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='pavarde',
            field=models.CharField(max_length=50, verbose_name='Pavardė'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='vardas',
            field=models.CharField(max_length=50, verbose_name='Vardas'),
        ),
        migrations.AlterField(
            model_name='vadovas',
            name='pavarde',
            field=models.CharField(max_length=50, verbose_name='Pavardė'),
        ),
        migrations.AlterField(
            model_name='vadovas',
            name='vardas',
            field=models.CharField(max_length=50, verbose_name='Vardas'),
        ),
        migrations.AlterField(
            model_name='vadovolaikas',
            name='vadovas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laikai', to='reservations.vadovas', verbose_name='Vadovas'),
        ),
        migrations.AlterField(
            model_name='vadovopertrauka',
            name='description',
            field=models.CharField(blank=True, max_length=100, verbose_name='Aprašymas'),
        ),
        migrations.AlterField(
            model_name='vadovopertrauka',
            name='end_time',
            field=models.TimeField(verbose_name='Pabaiga'),
        ),
        migrations.AlterField(
            model_name='vadovopertrauka',
            name='laikas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='reservations.vadovolaikas', verbose_name='Vadovo laikas'),
        ),
        migrations.AlterField(
            model_name='vadovopertrauka',
            name='start_time',
            field=models.TimeField(verbose_name='Pradžia'),
        ),
        migrations.AlterField(
            model_name='vadovorezervacija',
            name='cabinet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.cabinet', verbose_name='Kabinetas'),
        ),
        migrations.AlterField(
            model_name='vadovorezervacija',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Sukurta'),
        ),
        migrations.AlterField(
            model_name='vadovorezervacija',
            name='date',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='vadovorezervacija',
            name='mokytojas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vadovo_rezervacijos', to='reservations.teacher', verbose_name='Mokytojas'),
        ),
        migrations.AlterField(
            model_name='vadovorezervacija',
            name='time',
            field=models.TimeField(verbose_name='Laikas'),
        ),
        migrations.AlterField(
            model_name='vadovorezervacija',
            name='vadovas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rezervacijos', to='reservations.vadovas', verbose_name='Vadovas'),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='date',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='end_time',
            field=models.TimeField(verbose_name='Pabaiga'),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='interval',
            field=models.IntegerField(choices=[(15, '15 minučių'), (30, '30 minučių'), (45, '45 minutės'), (60, '60 minučių')], default=10, verbose_name='Laiko intervalas'),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='mokytojai',
            field=models.ManyToManyField(related_name='working_hours', to='reservations.teacher', verbose_name='Mokytojai'),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='start_time',
            field=models.TimeField(verbose_name='Pradžia'),
        ),
    ]
